/* 
    This is a program performing blind line emission searching in uv-fits data. 
    uv-fits file is the a fits format data table, generated by astronomical interferometry observations.
 
 */


#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <vector>
#include <iostream>
#include <iomanip>
#include "CrabFitsTableClass.h"


int main(int argc, char **argv)
{
    //
    // prepare variables
    char *cstrInputFilePath = NULL;
    char *cstrFitsExtNumber = (char *)"0";
    int   intHeaderComment = 1;
    int debug = 0;
    
    //
    // read user-input arguments
    for(int i=1; i<argc; i++) {
        // read extension parameter
        if(strncasecmp(argv[i],"-ext",4)==0 && i<argc-1) {
            i++; cstrFitsExtNumber = argv[i]; continue;
        }
        // read -header-no-comment option
        if(strncasecmp(argv[i],"-header-no",10)==0) { // -header-no-comment
            intHeaderComment = 0; continue;
        }
        // read -header-in-comment option
        if(strncasecmp(argv[i],"-header-in",10)==0) { // -header-in-comment
            intHeaderComment = 1; continue;
        }
        // read input fits file path
        if(cstrInputFilePath==NULL && i<=argc-1) {
            cstrInputFilePath = argv[i]; continue;
        }
    }
    
    //
    // read uv-fits data
    if(cstrInputFilePath!=NULL)
    {
        //
        // call readFitsTable and read uv-fits data
        int intFitsExtNumber = std::atoi(cstrFitsExtNumber);
        CrabFitsTableClass data = CrabFitsTableClass(cstrInputFilePath, intFitsExtNumber);
        
        
    }
    
    //
    // return
    return 0;
}
