#!/bin/bash
# 

if [[ $(uname) == "Darwin" ]]; then
    clang++ CrabFitsIO.cpp CrabImage.cpp main.cpp -o CrabPhotAperPhot_mac
else
    g++ CrabFitsIO.cpp CrabImage.cpp main.cpp -o CrabPhotAperPhot_linux_x86_64
fi



#cp CrabPhotAperPhot_mac ~/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_mac/CrabPhotAperPhot_mac
#cp CrabPhotAperPhot_mac ~/Cloud/Github/AlmaCosmos/Softwares/ds9_mac/CrabPhotAperPhot_mac
#cp CrabPhotAperPhot_mac ~/Cloud/Github/SpireLines/Softwares/ds9_mac/CrabPhotAperPhot_mac
#cp CrabPhotAperPhot_mac ~/Cloud/Github/Crab.Toolkit.PdBI/bin/bin_mac/CrabPhotAperPhot_mac

#cp CrabPhotAperPhot_linux_x86_64 ~/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_linux_Glibc_2.14/CrabPhotAperPhot_linux_x86_64
#cp CrabPhotAperPhot_linux_x86_64 ~/Cloud/Github/AlmaCosmos/Softwares/ds9_linux_Glibc_2.14/CrabPhotAperPhot_linux_x86_64
#cp CrabPhotAperPhot_linux_x86_64 ~/Cloud/Github/SpireLines/Softwares/ds9_linux_Glibc_2.14/CrabPhotAperPhot_linux_x86_64
#cp CrabPhotAperPhot_linux_x86_64 ~/Cloud/Github/Crab.Toolkit.PdBI/bin/bin_linux_Glibc_2.17/CrabPhotAperPhot_linux_x86_64
