#!/bin/bash
# 


if [[ $(uname) == "Darwin" ]]; then
    clang++ -I/usr/include/malloc/ main.cpp CrabFitsIO.cpp -o CrabFitsImageArithmetic_mac
    #cp -i CrabFitsImageArithmetic_mac ~/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_mac/
fi

if [[ $(uname) == "Linux" ]]; then
    g++ main.cpp CrabFitsIO.cpp -o CrabFitsImageArithmetic_linux_x86_64
fi


