#!/bin/bash
# 

List_dirs=( "CrabFitsHeader" \
            "CrabFitsImageArithmetic" \
            "CrabFitsImageCopy" \
            "CrabFitsImageCrop" \
          )

for List_dir in "${List_dirs[@]}"; do
    echo "cp -i \"${List_dir}/${List_dir}_linux_x86_64_ldd_2_15_v20170807\" \"$HOME/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_linux_Glibc_2.14/${List_dir}_linux_x86_64\""
          cp -i  "${List_dir}/${List_dir}_linux_x86_64_ldd_2_15_v20170807"   "$HOME/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_linux_Glibc_2.14/${List_dir}_linux_x86_64"
    
    echo "cp -i \"${List_dir}/${List_dir}_mac_v20170807\" \"$HOME/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_mac/${List_dir}_mac\""
          cp -i  "${List_dir}/${List_dir}_mac_v20170807"   "$HOME/Cloud/Github/DeepFields.SuperDeblending/Softwares/ds9_mac/${List_dir}_mac"
done


#cp CrabFitsImageFromGildasMapping/pdbi-lmv-to-fits
#cp CrabFitsImageFromGildasMapping/pdbi-uvt-to-fits

