#!/bin/bash
# 

#rm CrabBlobDetector_mac

if [[ $(uname) == "Darwin" ]]; then
    clang++  -I/usr/include/malloc/ -I../ -I../../../CrabIO/CrabFitsIO -I../../../CrabIO/CrabImage -I../../../CrabIO/CrabString -I../../../CrabIO/CrabTable -L../ ../../../CrabIO/CrabFitsIO/CrabFitsIO.cpp ../../../CrabIO/CrabImage/CrabImage.cpp main.cpp -o CrabBlobDetector_mac
else
    g++  -std=c++11  -I/usr/include/malloc/ -I../ -I../../../CrabIO/CrabFitsIO -I../../../CrabIO/CrabImage -I../../../CrabIO/CrabString -I../../../CrabIO/CrabTable -L../ ../../../CrabIO/CrabFitsIO/CrabFitsIO.cpp ../../../CrabIO/CrabImage/CrabImage.cpp main.cpp -o CrabBlobDetector_linux_x86_64
fi

# ./CrabBlobDetector_mac all.irac.1.mosaic.cut_1000_1000_1999_1999.fits

# ./CrabBlobDetector_mac  velo_bin_1.lmv.fits  "$@" 

# CrabFitsImageArithmetic velo_bin_1.lmv.fits times 0.9277206823935E-12 velo_bin_1.lmv.2.fits
# sethead velo_bin_1.lmv.2.fits BSCALE=1 

#./CrabBlobDetector_mac  velo_bin_1.lmv.2.fits  "$@"

#ds9 velo_bin_1.lmv.fits  -regions load ds9.reg

