#!/bin/bash
# 

./do_Compile

# test copy to multi-extension fits file

cp input.fits output.fits # an empty image

./CrabFitsImageCopy_mac input.fits -ext 2 -rect 30 30 260 260 output.fits -ext 3 -rect 30 30 300 300 -debug # test copy a patch of image, if output rect is larger than input rect, then refine to input rect. 

ds9 -tile mode column -lock frame image -lock scale yes -lock colorbar yes -cmap aips0 -multiframe input.fits output.fits &

