#!/bin/bash
# 

./do_Compile

cp output_backup.fits output.fits # an empty image

./CrabFitsImageCopy_mac input.fits -ext 3 output.fits -debug

ds9 -tile mode column -lock frame image -lock scale yes -lock colorbar yes -multiframe input.fits output.fits &

