#!/bin/bash
# 

./do_Compile

cp output_backup.fits output.fits # an empty image

./CrabFitsImageCopy_mac input.fits -ext 3 -rect 30 30 60 60 output.fits -rect 31 31 61 61 -debug # test copy a patch of image, shift by +1,+1 pixel

ds9 -tile mode column -lock frame image -lock scale yes -lock colorbar yes -multiframe input.fits output.fits &

