#!/bin/bash
# 

./do_Compile

cp output_backup.fits output.fits # an empty image

./CrabFitsImageCopy_mac input.fits -ext 3 -rect 30 30 160 160 output.fits -rect 30 30 120 120 -debug # test copy a patch of image, cut to smaller

ds9 -tile mode column -lock frame image -lock scale yes -lock colorbar yes -cmap aips0 -multiframe input.fits output.fits &

